version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    ignore:
      # List of dependencies to ignore updates for
      # - dependency-name: "github.com/foo/bar"
