---
modbus:
  path: /dev/ttyUSB0
  baudRate: 9600
  dataBits: 8
  stopBits: 1
  parity: N
  timeout: 5s
  unitId: 1
gauges:
  - name: "battery_volts"
    help: "How many volts are in the battery"
    address: 0x101
    multiplier: 0.1
  - name: "battery_charge_amps"
    help: "How many amps are going into the battery"
    address: 0x102
    multiplier: 0.01
  - name: "battery_capacity_percent"
    help: "The percentage of battery's remaining capacity"
    address: 0x100
  - name: "solar_volts"
    help: "How many volts are coming from solar"
    address: 0x107
    multiplier: 0.1
  - name: "solar_amps"
    help: "How many amps are coming from solar"
    address: 0x108
    multiplier: 0.01
  - name: "charge_watts"
    help: "charging power"
    address: 0x109
  - name: "inside_case_temp"
    help: "Temperature inside case, celsius"
    address: 0x103
    byte: 0
    signed: true
  - name: "battery_temp"
    help: "Temperature at the battery probe, celsius"
    address: 0x103
    byte: 1
    signed: true
  - name: "charge_status"
    help: "Charging status"
    address: 0x120
    byte: 1
    states:
      - name: "none"
        value: 0
      - name: "charging"
        value: 1
      - name: "mppt"
        value: 2
      - name: "equalize"
        value: 3
      - name: "boost"
        value: 4
      - name: "float"
        value: 5
      - name: "current limiting"
        value: 6
