name: build + test + lint
on:
  pull_request:
    paths:
      - "go.sum"
      - "go.mod"
      - "**.go"
      - "Makefile"
      - ".github/workflows/ci.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: make build
      - run: make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.45.2